#!/usr/bin/env python3
"""Run the repository's ordinary verification tools without hiding failed steps."""

import argparse
import json
import os
import platform
from pathlib import Path
import subprocess
import sys
import tempfile
import time
import zipfile

sys.path.insert(0, str(Path(__file__).resolve().parent))

from verification_inputs import CHECK_VERSION, digest, file_hash, git_identity, input_identity
from xml.etree import ElementTree


def owned_sources(root):
    """List all owned Python runtime files, including never-imported modules."""
    sources = set(root.glob("dphtools/**/*.py")) | set(root.glob("tools/**/*.py"))
    sources.discard(root / "dphtools/_version.py")  # Generated by Versioneer.
    sources.add(root / "tools/delivery")
    return sorted(path.relative_to(root).as_posix() for path in sources)


def require(condition, message):
    """Fail a report check with a concrete diagnostic."""
    if not condition:
        raise ValueError(message)


def validate_reports(directory, sources):
    """Reject absent tests, skipped behavior, incomplete measurement, and omissions."""
    try:
        junit = ElementTree.parse(directory / "pytest.xml")
        suites = list(junit.iter("testsuite"))
        cases = list(junit.iter("testcase"))
        require(bool(suites) and bool(cases), "No tests ran")
        require(sum(int(s.attrib["tests"]) for s in suites) == len(cases), "Test count mismatch")
        for field in ("failures", "errors", "skipped"):
            require(all(int(s.attrib[field]) == 0 for s in suites), f"Tests report {field}")
        require(
            not any(
                case.find(tag) is not None
                for case in cases
                for tag in ("failure", "error", "skipped")
            ),
            "Test cases contain failures, errors, or skips",
        )
        coverage = json.loads((directory / "coverage.json").read_text())
        require(
            coverage["meta"]["branch_coverage"] is True,
            "Branch measurement is unsupported or absent",
        )
        files = {name.replace("\\", "/"): value for name, value in coverage["files"].items()}
        require(set(files) == set(sources), "Coverage file set differs from owned runtime sources")
        fields = (
            "num_statements",
            "covered_lines",
            "missing_lines",
            "excluded_lines",
            "num_branches",
            "covered_branches",
            "missing_branches",
        )
        for name, result in files.items():
            counts = result["summary"]
            require(
                all(type(counts[f]) is int and counts[f] >= 0 for f in fields),
                f"Invalid counts: {name}",
            )
            require(counts["excluded_lines"] == 0, f"Excluded statements: {name}")
            require(
                counts["covered_lines"] == counts["num_statements"]
                and counts["missing_lines"] == 0,
                f"Incomplete statement coverage: {name}",
            )
            require(
                counts["covered_branches"] == counts["num_branches"]
                and counts["missing_branches"] == 0,
                f"Incomplete branch coverage: {name}",
            )
            require(
                not result["missing_lines"] and not result["missing_branches"],
                f"Missing coverage: {name}",
            )
        totals = coverage["totals"]
        require(totals["num_statements"] > 0, "Empty statement measurement")
        for field in fields:
            require(
                totals[field] == sum(value["summary"][field] for value in files.values()),
                f"Coverage totals mismatch: {field}",
            )
        xml = ElementTree.parse(directory / "coverage.xml").getroot()
        require(xml.tag == "coverage", "Invalid coverage XML root")
        for attribute, field in (
            ("lines-valid", "num_statements"),
            ("lines-covered", "covered_lines"),
            ("branches-valid", "num_branches"),
            ("branches-covered", "covered_branches"),
        ):
            require(
                int(xml.attrib[attribute]) == totals[field], f"Coverage XML mismatch: {attribute}"
            )
    except (
        OSError,
        ValueError,
        KeyError,
        TypeError,
        AttributeError,
        ElementTree.ParseError,
    ) as error:
        print(f"Report validation failed: {error}", flush=True)
        return 1
    return 0


# Dependencies identify successful prerequisites; fresh coverage is a separate
# prerequisite so failed tests retain diagnostics without authorizing old data.
DEPENDENCIES = {
    "build": ("preflight", "format", "lint", "docstrings", "types", "audit"),
    "wheel-artifacts": ("build",),
    "install": ("wheel-artifacts",),
    "coverage-erase": ("install",),
    "tests": ("coverage-erase",),
    "coverage-combine": ("coverage-data",),
    "coverage-json": ("coverage-combine",),
    "coverage-xml": ("coverage-combine",),
    "coverage-report": ("coverage-combine",),
    "report-validation": ("coverage-json", "coverage-xml", "coverage-report"),
}


class VerificationRun:
    """Execute dependency-aware steps and persist each completed receipt atomically."""

    def __init__(self, root, mode, directory=None):
        self.started = time.monotonic()
        self.root = Path(root)
        self.mode = mode
        reports = self.root / "reports/verification"
        reports.mkdir(parents=True, exist_ok=True)
        self.directory = Path(directory or tempfile.mkdtemp(prefix=f"{mode}-", dir=reports))
        self.directory.mkdir(parents=True, exist_ok=True)
        require(not any(self.directory.iterdir()), "Report directory must be empty")
        self.sources = owned_sources(self.root)
        self.identity = input_identity(self.root, self.sources)
        self.env = dict(os.environ, MPLBACKEND="Agg", PYTHONHASHSEED="0")
        for variable in (
            "OPENBLAS_NUM_THREADS",
            "OMP_NUM_THREADS",
            "MKL_NUM_THREADS",
            "VECLIB_MAXIMUM_THREADS",
            "NUMEXPR_NUM_THREADS",
            "BLIS_NUM_THREADS",
        ):
            self.env[variable] = "1"
        self.env.setdefault("PIP_COMPILE", "0")
        self.env["DPHTOOLS_COVERAGE_ROOT"] = str(self.root.resolve())
        self.env["COVERAGE_FILE"] = str(self.directory / ".coverage")
        self.env["COVERAGE_RCFILE"] = str(self.root / "setup.cfg")
        self.steps = []
        self.complete = False
        self.save()
        print(
            f"verification: mode={mode} python={sys.executable} "
            f"platform={platform.platform()} reports: {self.directory}",
            flush=True,
        )

    def save(self):
        """Replace the receipt only after its complete new JSON has been written."""
        record = {
            "document_version": CHECK_VERSION,
            "mode": self.mode,
            "complete": self.complete,
            "duration_seconds": time.monotonic() - self.started,
            "outcome": (
                (
                    "passed"
                    if all(step["state"] in ("passed", "reused") for step in self.steps)
                    else "failed"
                )
                if self.complete
                else "incomplete"
            ),
            "python": sys.executable,
            "platform": platform.platform(),
            "identity": self.identity,
            "identity_digest": digest(self.identity),
            "steps": self.steps,
            "failed": [
                step["name"] for step in self.steps if step["state"] not in ("passed", "reused")
            ],
            "measurement_limits": [
                "Git shell-hook statement/branch coverage is unsupported by coverage.py."
            ],
        }
        record["receipt_digest"] = digest(record)
        temporary = self.directory / "checks.json.tmp"
        temporary.write_text(json.dumps(record, indent=2) + "\n", encoding="utf-8")
        temporary.replace(self.directory / "checks.json")

    def run_step(
        self,
        name,
        command=None,
        dependencies=None,
        action=None,
        reason=None,
        identity=None,
        env=None,
    ):
        """Run an authorized step, or record which prerequisites blocked its execution."""
        self.complete = False
        self.save()
        dependencies = tuple(DEPENDENCIES.get(name, ()) if dependencies is None else dependencies)
        states = {step["name"]: step["state"] for step in self.steps}
        blocked = [
            f"{dependency}: {states.get(dependency, 'absent')}"
            for dependency in dependencies
            if states.get(dependency) not in ("passed", "reused")
        ]
        if reason:
            blocked.append(reason)
        started = time.monotonic()
        step = {
            "name": name,
            "command": command,
            "dependencies": list(dependencies),
            "blocking_reasons": blocked,
            "input_identity": identity or self.identity,
            "input_digest": digest(identity or self.identity),
        }
        print(f"\n== {name} ==", flush=True)
        with (self.directory / f"{name}.log").open("w", encoding="utf-8") as log:
            if blocked:
                print("Blocked: " + "; ".join(blocked), file=log, flush=True)
                print("Blocked: " + "; ".join(blocked), flush=True)
                status = None
            else:
                try:
                    if command is None:
                        status = action()
                    else:
                        with subprocess.Popen(
                            command,
                            cwd=self.root,
                            env=env or self.env,
                            stdout=subprocess.PIPE,
                            stderr=subprocess.STDOUT,
                            text=True,
                            encoding="utf-8",
                            errors="backslashreplace",
                            bufsize=1,
                        ) as child:
                            for output in child.stdout:
                                log.write(output)
                                log.flush()
                                print(output, end="", flush=True)
                            status = child.wait()
                except (OSError, ValueError) as error:
                    print(str(error), file=log, flush=True)
                    print(str(error), flush=True)
                    status = 1
            step.update(
                returncode=status,
                duration_seconds=time.monotonic() - started,
                state="blocked" if blocked else ("passed" if status == 0 else "failed"),
            )
        step["log"] = {"path": f"{name}.log", "sha256": file_hash(self.directory / f"{name}.log")}
        self.steps.append(step)
        self.save()
        return step

    def module(self, name, arguments, **kwargs):
        """Run a module with the verifier's selected interpreter."""
        return self.run_step(name, [sys.executable, "-m", *arguments], **kwargs)

    def finish(self):
        """Return a failing status whenever any step failed or was blocked."""
        failed = [step["name"] for step in self.steps if step["state"] not in ("passed", "reused")]
        self.complete = True
        self.save()
        print(
            f"\nverification: {'FAIL' if failed else 'PASS'}; "
            f"failed steps: {', '.join(failed) or 'none'}; reports: {self.directory}",
            flush=True,
        )
        return int(bool(failed))


LOCK_PROBE = r"""
from importlib import metadata
import importlib
from pathlib import Path
import sys
from packaging.requirements import Requirement
modules = {"black": "black", "flake8": "flake8", "pydocstyle": "pydocstyle",
           "pytest": "pytest", "coverage": "coverage", "mypy": "mypy",
           "pip-audit": "pip_audit", "build": "build", "numpy": "numpy",
           "scipy": "scipy", "matplotlib": "matplotlib", "scikit-image": "skimage"}
checked = 0
for line in Path(sys.argv[1]).read_text().splitlines():
    if not line or line[0].isspace() or line.startswith("#"):
        continue
    requirement = Requirement(line.rstrip("\\ "))
    if requirement.marker is not None and not requirement.marker.evaluate():
        continue
    checked += 1
    if sys.argv[2] == "imports":
        if requirement.name in modules:
            importlib.import_module(modules[requirement.name])
    else:
        observed = metadata.version(requirement.name)
        if str(requirement.specifier) != "==" + observed:
            raise ValueError(f"locked dependency {requirement.name}: expected "
                             f"{requirement.specifier}, installed {observed}")
if checked == 0:
    raise ValueError("No applicable locked dependencies")
print("locked " + sys.argv[2] + " checked")
"""


def preflight(run):
    """Probe locked imports and real nested venv/pip behavior in disposable paths."""
    run.run_step(
        "interpreter",
        [
            sys.executable,
            "-c",
            "import sys; print(sys.version); assert sys.version_info >= (3, 10)",
        ],
    )
    lock = str(run.root / "requirements-dev.lock")
    for name, probe in (("locked-dependencies", "dependencies"), ("imports", "imports")):
        run.run_step(
            name, [sys.executable, "-c", LOCK_PROBE, lock, probe], dependencies=("interpreter",)
        )
    with tempfile.TemporaryDirectory(prefix="nested-", dir=run.directory) as temporary:
        nested = Path(temporary) / "nested"
        executable = "Scripts/python.exe" if os.name == "nt" else "bin/python"
        clean = dict(run.env)
        clean.pop("PYTHONPATH", None)
        # Installing a tiny local wheel exercises pip without network or system writes.
        wheel = Path(temporary) / "verification_probe-1.0-py3-none-any.whl"
        with zipfile.ZipFile(wheel, "w") as archive:
            archive.writestr("verification_probe.py", "VALUE = 42\n")
            archive.writestr(
                "verification_probe-1.0.dist-info/METADATA",
                "Metadata-Version: 2.1\nName: verification-probe\nVersion: 1.0\n",
            )
            archive.writestr(
                "verification_probe-1.0.dist-info/WHEEL",
                "Wheel-Version: 1.0\nGenerator: verification\n"
                "Root-Is-Purelib: true\nTag: py3-none-any\n",
            )
            archive.writestr("verification_probe-1.0.dist-info/RECORD", "")
        builder = "import sys, venv; venv.EnvBuilder(with_pip=True).create(sys.argv[1])"
        run.run_step(
            "venv",
            [sys.executable, "-c", builder, str(nested)],
            dependencies=("interpreter",),
            env=clean,
        )
        run.run_step(
            "nested-venv",
            [
                str(nested / executable),
                "-c",
                "import sys; assert sys.prefix != sys.base_prefix; print(sys.prefix)",
            ],
            dependencies=("venv",),
            env=clean,
        )
        run.run_step(
            "nested-pip",
            [
                str(nested / executable),
                "-m",
                "pip",
                "install",
                "--disable-pip-version-check",
                "--no-index",
                "--no-deps",
                str(wheel),
            ],
            dependencies=("nested-venv",),
            env=clean,
        )
        run.run_step(
            "nested-import",
            [
                str(nested / executable),
                "-c",
                "import verification_probe; assert verification_probe.VALUE == 42",
            ],
            dependencies=("nested-pip",),
            env=clean,
        )
    run.run_step(
        "preflight",
        action=lambda: 0,
        dependencies=("interpreter", "locked-dependencies", "imports", "nested-import"),
    )


def prepare_checks(run):
    """Run quality gates and retain exactly one freshly built wheel."""
    distributions = run.directory / "dist"
    runtime_tools = [source for source in run.sources if source.startswith("tools/")]
    run.module("types", ["mypy", "--follow-untyped-imports", "dphtools", *runtime_tools])
    run.module("audit", ["pip_audit", "--require-hashes", "-r", "requirements-dev.lock"])
    build_identity = dict(run.identity, git=git_identity(run.root))
    run.module(
        "build",
        ["build", "--no-isolation", "--outdir", str(distributions)],
        identity=build_identity,
    )
    wheels = sorted(distributions.glob("*.whl"))
    artifacts = {path.name: file_hash(path) for path in distributions.glob("*") if path.is_file()}

    def check_wheel():
        require(len(wheels) == 1, f"Expected exactly one built wheel; found {len(wheels)}")
        return 0

    run.run_step(
        "wheel-artifacts", action=check_wheel, identity=dict(build_identity, artifacts=artifacts)
    )
    return wheels, artifacts


def full_checks(run, workers=1):
    """Build one wheel, install it, and test with fresh complete owned measurement."""
    wheels, artifacts = prepare_checks(run)
    run.module(
        "install",
        [
            "pip",
            "install",
            "--no-deps",
            "--no-build-isolation",
            "--force-reinstall",
            *map(str, wheels),
        ],
        identity=dict(run.identity, git=git_identity(run.root), artifacts=artifacts),
    )
    run.module("coverage-erase", ["coverage", "erase"])
    from verification_parallel import parallel_test_step

    parallel_test_step(run, workers)
    fresh = any(path.is_file() for path in run.directory.glob(".coverage*"))
    run.run_step(
        "coverage-data",
        action=lambda: 0,
        dependencies=("coverage-erase",),
        reason=None if fresh else "No fresh coverage data produced by this run",
    )
    process_coverage(run)


def process_coverage(run):
    """Combine fresh parent/child data and enforce the exact owned-source gate."""
    run.module("coverage-combine", ["coverage", "combine"])
    run.module(
        "coverage-json",
        ["coverage", "json", "-o", str(run.directory / "coverage.json"), *run.sources],
    )
    run.module(
        "coverage-xml",
        ["coverage", "xml", "-o", str(run.directory / "coverage.xml"), *run.sources],
    )
    run.module("coverage-report", ["coverage", "report", "--fail-under=100", *run.sources])
    run.run_step("report-validation", action=lambda: validate_reports(run.directory, run.sources))


def fast_checks(run, reuse=None):
    """Run independent cheap tools even if another cheap check fails."""
    runtime_tools = [source for source in run.sources if source.startswith("tools/")]
    lint_paths = ["dphtools", "tests", *runtime_tools, "setup.py", "versioneer.py"]
    run.module("format", ["black", "--check", "--line-length", "99", *lint_paths, "notebooks"])
    run.module("lint", ["flake8", *lint_paths])
    if run.mode != "fast":
        run.module("docstrings", ["pydocstyle", "--count", "dphtools"])
        return
    from verification_reuse import reusable, runtime_identity

    command = [sys.executable, "-m", "pydocstyle", "--count", "dphtools"]
    started = time.monotonic()
    identity = dict(run.identity, runtime=runtime_identity(run.root))
    provenance, rejection = reusable(reuse, identity, command) if reuse else (None, None)
    if provenance:
        log = run.directory / "docstrings.log"
        log.write_text(
            "Reused original docstrings evidence: " + provenance["receipt"] + "\n",
            encoding="utf-8",
        )
        run.steps.append(
            {
                "name": "docstrings",
                "command": command,
                "state": "reused",
                "returncode": None,
                "duration_seconds": time.monotonic() - started,
                "dependencies": [],
                "blocking_reasons": [],
                "input_identity": identity,
                "input_digest": digest(identity),
                "provenance": provenance,
                "log": {"path": log.name, "sha256": file_hash(log)},
            }
        )
        run.save()
        print("docstrings: reused original receipt " + provenance["receipt"], flush=True)
    else:
        identity_seconds = time.monotonic() - started
        step = run.run_step("docstrings", command, identity=identity)
        step["duration_seconds"] += identity_seconds
        if rejection:
            step["reuse_rejection"] = rejection
        run.save()


def main():
    """Run host checks or collect, execute, and aggregate isolated CI shards."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "mode", choices=("preflight", "fast", "full", "collect", "shard", "aggregate")
    )
    parser.add_argument("--report-dir", type=Path)
    parser.add_argument("--manifest", type=Path)
    parser.add_argument("--shard-index", type=int)
    parser.add_argument("--shard-count", type=int, choices=(2, 4, 8), default=2)
    parser.add_argument("--shards", nargs="+", type=Path)
    parser.add_argument("--durations", nargs="+", type=Path, default=[])
    parser.add_argument("--reuse", type=Path)
    parser.add_argument("--workers", type=int, choices=range(1, 9), default=8)
    arguments = parser.parse_args()
    mode = arguments.mode
    if arguments.reuse is not None and mode != "fast":
        parser.error("--reuse is allowed only for fast; full CI and release evidence run fresh")
    if mode in ("shard", "aggregate") and arguments.manifest is None:
        parser.error("--manifest is required")
    if mode == "shard" and arguments.shard_index not in range(arguments.shard_count):
        parser.error("--shard-index must be between zero and --shard-count minus one")
    if mode == "aggregate" and arguments.shards is None:
        parser.error("--shards is required")
    run = VerificationRun(Path(__file__).resolve().parents[1], mode, arguments.report_dir)
    print(
        "Host verification only; CI verifies its operating-system matrix separately.", flush=True
    )
    print(
        "Measurement limit: coverage.py cannot measure Git shell-hook statements/branches.",
        flush=True,
    )
    if mode in ("preflight", "full"):
        preflight(run)
    if mode in ("fast", "full"):
        fast_checks(run, arguments.reuse)
    if mode == "full":
        full_checks(run, arguments.workers)
    if mode in ("collect", "shard", "aggregate"):
        from verification_shards import run_sharded

        run_sharded(run, arguments)
    return run.finish()


if __name__ == "__main__":
    raise SystemExit(main())
