#!/usr/bin/env python3
"""Run the repository's ordinary verification tools without hiding failed steps."""

import argparse
import json
import os
import platform
from pathlib import Path
import subprocess
import sys
import tempfile
from xml.etree import ElementTree


def owned_sources(root):
    """List all owned Python runtime files, including never-imported modules."""
    sources = set(root.glob("dphtools/**/*.py")) | set(root.glob("tools/**/*.py"))
    sources.discard(root / "dphtools/_version.py")  # Generated by Versioneer.
    sources.add(root / "tools/delivery")
    return sorted(path.relative_to(root).as_posix() for path in sources)


def require(condition, message):
    """Fail a report check with a concrete diagnostic."""
    if not condition:
        raise ValueError(message)


def validate_reports(directory, sources):
    """Reject absent tests, skipped behavior, incomplete measurement, and omissions."""
    try:
        junit = ElementTree.parse(directory / "pytest.xml")
        suites = list(junit.iter("testsuite"))
        cases = list(junit.iter("testcase"))
        require(bool(suites) and bool(cases), "No tests ran")
        require(sum(int(s.attrib["tests"]) for s in suites) == len(cases), "Test count mismatch")
        for field in ("failures", "errors", "skipped"):
            require(all(int(s.attrib[field]) == 0 for s in suites), f"Tests report {field}")
        require(
            not any(
                case.find(tag) is not None
                for case in cases
                for tag in ("failure", "error", "skipped")
            ),
            "Test cases contain failures, errors, or skips",
        )
        coverage = json.loads((directory / "coverage.json").read_text())
        require(
            coverage["meta"]["branch_coverage"] is True,
            "Branch measurement is unsupported or absent",
        )
        files = {name.replace("\\", "/"): value for name, value in coverage["files"].items()}
        require(set(files) == set(sources), "Coverage file set differs from owned runtime sources")
        fields = (
            "num_statements",
            "covered_lines",
            "missing_lines",
            "excluded_lines",
            "num_branches",
            "covered_branches",
            "missing_branches",
        )
        for name, result in files.items():
            counts = result["summary"]
            require(
                all(type(counts[f]) is int and counts[f] >= 0 for f in fields),
                f"Invalid counts: {name}",
            )
            require(counts["excluded_lines"] == 0, f"Excluded statements: {name}")
            require(
                counts["covered_lines"] == counts["num_statements"]
                and counts["missing_lines"] == 0,
                f"Incomplete statement coverage: {name}",
            )
            require(
                counts["covered_branches"] == counts["num_branches"]
                and counts["missing_branches"] == 0,
                f"Incomplete branch coverage: {name}",
            )
            require(
                not result["missing_lines"] and not result["missing_branches"],
                f"Missing coverage: {name}",
            )
        totals = coverage["totals"]
        require(totals["num_statements"] > 0, "Empty statement measurement")
        for field in fields:
            require(
                totals[field] == sum(value["summary"][field] for value in files.values()),
                f"Coverage totals mismatch: {field}",
            )
        xml = ElementTree.parse(directory / "coverage.xml").getroot()
        require(xml.tag == "coverage", "Invalid coverage XML root")
        for attribute, field in (
            ("lines-valid", "num_statements"),
            ("lines-covered", "covered_lines"),
            ("branches-valid", "num_branches"),
            ("branches-covered", "covered_branches"),
        ):
            require(
                int(xml.attrib[attribute]) == totals[field], f"Coverage XML mismatch: {attribute}"
            )
    except (
        OSError,
        ValueError,
        KeyError,
        TypeError,
        AttributeError,
        ElementTree.ParseError,
    ) as error:
        print(f"Report validation failed: {error}", flush=True)
        return 1
    return 0


def main():
    """Run fast checks or the complete host gate, returning failure for any failed step."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("mode", choices=("fast", "full"))
    mode = parser.parse_args().mode
    root = Path(__file__).resolve().parents[1]
    reports = root / "reports/verification"
    reports.mkdir(parents=True, exist_ok=True)
    directory = Path(tempfile.mkdtemp(prefix=f"{mode}-", dir=reports))
    distributions = directory / "dist"
    env = dict(os.environ, MPLBACKEND="Agg", PYTHONHASHSEED="0")
    env["COVERAGE_FILE"] = str(directory / ".coverage")
    env["COVERAGE_RCFILE"] = str(root / "setup.cfg")
    sources = owned_sources(root)
    runtime_tools = [source for source in sources if source.startswith("tools/")]
    lint_paths = ["dphtools", "tests", *runtime_tools, "setup.py", "versioneer.py"]
    commands = [
        ("format", ["black", "--check", "--line-length", "99", *lint_paths, "notebooks"]),
        ("lint", ["flake8", *lint_paths]),
        ("docstrings", ["pydocstyle", "--count", "dphtools"]),
    ]
    if mode == "full":
        commands += [
            ("types", ["mypy", "--follow-untyped-imports", "dphtools", *runtime_tools]),
            ("audit", ["pip_audit", "--require-hashes", "-r", "requirements-dev.lock"]),
            ("build", ["build", "--no-isolation", "--outdir", str(distributions)]),
            (
                "install",
                ["pip", "install", "--no-deps", "--no-build-isolation", "--force-reinstall"],
            ),
            ("coverage-erase", ["coverage", "erase"]),
            (
                "tests",
                [
                    "coverage",
                    "run",
                    "-m",
                    "pytest",
                    "--doctest-modules",
                    "dphtools",
                    "tests",
                    "-ra",
                    f"--junitxml={directory / 'pytest.xml'}",
                ],
            ),
            ("coverage-combine", ["coverage", "combine"]),
            (
                "coverage-json",
                ["coverage", "json", "-o", str(directory / "coverage.json"), *sources],
            ),
            ("coverage-xml", ["coverage", "xml", "-o", str(directory / "coverage.xml"), *sources]),
            ("coverage-report", ["coverage", "report", "--fail-under=100", *sources]),
        ]
    print(
        f"verification: mode={mode} python={sys.executable} platform={platform.platform()}",
        flush=True,
    )
    print(
        "Host verification only; CI verifies its operating-system matrix separately.", flush=True
    )
    print(
        "Measurement limit: coverage.py cannot measure the Git shell hooks' statements/branches.",
        flush=True,
    )
    steps = []
    for name, arguments in commands:
        if name == "install":
            arguments = [*arguments, *map(str, sorted(distributions.glob("*.whl")))]
        command = [sys.executable, "-m", *arguments]
        print(f"\n== {name} ==", flush=True)
        try:
            result = subprocess.run(
                command,
                cwd=root,
                env=env,
                stdout=subprocess.PIPE,
                stderr=subprocess.STDOUT,
                text=True,
                errors="backslashreplace",
            )
            output, status = result.stdout, result.returncode
        except OSError as error:
            output, status = str(error), 1
        (directory / f"{name}.log").write_text(output, encoding="utf-8")
        print(output, end="" if output.endswith("\n") else "\n", flush=True)
        steps.append({"name": name, "command": command, "returncode": status})
    if mode == "full":
        status = validate_reports(directory, sources)
        steps.append({"name": "report-validation", "command": None, "returncode": status})
    failed = [step["name"] for step in steps if step["returncode"] != 0]
    record = {
        "document_version": "1.0",
        "mode": mode,
        "python": sys.executable,
        "platform": platform.platform(),
        "steps": steps,
        "failed": failed,
        "measurement_limits": [
            "Git shell-hook statement/branch coverage is unsupported by coverage.py."
        ],
    }
    (directory / "checks.json").write_text(json.dumps(record, indent=2) + "\n", encoding="utf-8")
    outcome = "FAIL" if failed else "PASS"
    print(
        f"\nverification: {outcome}; failed steps: {', '.join(failed) or 'none'}; reports: {directory}",
        flush=True,
    )
    return int(bool(failed))


if __name__ == "__main__":
    raise SystemExit(main())
